/*Project Euler - http://www.projecteuler.net
The Odin Project - http://www.theodinproject.com/web-development-101/javascript-basics?ref=lnav
Problem 2
Each new term in the Fibonacci sequence is generated by adding the
previous two terms. By starting with 1 and 2, the first 10 terms
will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not
exceed four million, find the sum of the even-valued terms.
*/

var evenFib = function(topNum) {
    sum = 0;
    var last = 1;
    var i = 2;
    var placeHolder = "";
    while (i < topNum) {
        if (i % 2 === 0) {
            sum+=i;
        }
        console.log(i);
        placeHolder = i;
        i += last;
        last = placeHolder;
    }
    return sum;
};

evenFib(90);